# Generated by Django 5.1.6 on 2025-02-27 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
